### ISSUE TITLE
功能建议：丰富预设的搜索引擎种类以及相应的自动补全功能

### ISSUE THREAD

**Issue by xymeng16** [awaLiny2333/LinysBrowser_NEXT#11]
Hello，又是我来骚扰：）

<img width="355" alt="image" src="https://github.com/user-attachments/assets/c3da5f2e-0328-48c0-a116-ba936385c3c1">

如图所示，希望可以多预设几种搜索引擎（默认的必应，谷歌，百度等）以及实现相应的自动补全功能。

如果需要，我可以参与开发然后提PR（不过不知道多久能搞定哈）。

### 相关资料（未公开，不过firefox也是这么用的👀）：

Google的自动补全API：
- https://www.google.com/complete/search?client=firefox&q=hello (JSON)
- https://suggestqueries.google.com/complete/search?client=firefox&q=hello (JSON)
- https://clients1.google.com/complete/search?hl=zh&output=toolbar&q=hello (XML)

Bing的自动补全API：
- https://api.bing.com/qsml.aspx?Market=zh-CN&q=test (XML)

**Comment by awaLiny2333** [comment]
喔～自动补全！这个东西在 Liny 自己的日常里好像感知不强，可能因为平时搜的东西都太怪了……（逃
不过这几个 API 倒是好成熟的样子 ヽ(￣ω￣(￣ω￣〃)ゝ （只是国内环境上 Google 有点困难（（（

（不过突然想到，话说，有没有可能用本地的小艺智能来提出自动补全的提示（？
（如果，如果可以的话，能够根据小艺见闻的大数据，结合一些本地的偏好之类进行猜测，没准也是很有意思的体验（？
（比如在读论文的时候小窗呼出浏览器，就能分析屏幕上的文字，针对这个提出建议……
（不过可能会有隐私上的问题（

总之……这是个好主意！但是可能还需要一些时间研究下……
感激不尽！！ฅ•ω•ฅ

**Comment by awaLiny2333** [comment]
顺便想到，搜索引擎快捷切换估计也会在近期（说不准）做出来！:D

**Comment by xymeng16** [comment]
确实看个人需求，我看目前输入搜素内容之后出现的是和内容相关的历史记录。其实可以结合一下，比如出现两个相关历史，下面有三四个由这些api提供的自动补全。我昨天尝试着写了一个切换搜索引擎和自动补全（目前做了谷歌和必应）的简单实现，目前看没什么问题。（见下图）
![image](https://github.com/user-attachments/assets/d6d3076a-c9bd-4d93-858a-572db4c854e2)
![image](https://github.com/user-attachments/assets/f9c7cb67-8471-4e58-b894-b9dbb5c8ffc3)

> （比如在读论文的时候小窗呼出浏览器，就能分析屏幕上的文字，针对这个提出建议……
>（不过可能会有隐私上的问题（

至于类似这种操作，即使不考虑隐私问题，我也有下面两方面的担忧：
- 华为不允许[**手机和平板**](https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-screenshot-V5#screenshotpick)上的用户应用调用截图API，所以只能靠手动截图再传给浏览器。如此而言，用户完全可以直接长按小白条唤出一个权限更高的小艺来读屏-解析。
- 个人感觉，一个浏览器，最重要的还是维护好核心功能，也就是网页浏览。对于一个已经可以很简洁的完成的操作，没必要再做一个小艺的壳子放在应用内？

> 
顺便想到，搜索引擎快捷切换估计也会在近期（说不准）做出来！:D

不知道你说的这个快捷切换，指的是不是在搜索的时候可以选择不同的搜索引擎？听上去很棒：）

**Comment by awaLiny2333** [comment]
> 确实看个人需求，我看目前输入搜素内容之后出现的是和内容相关的历史记录。其实可以结合一下，比如出现两个相关历史，下面有三四个由这些api提供的自动补全。我昨天尝试着写了一个切换搜索引擎和自动补全（目前做了谷歌和必应）的简单实现，目前看没什么问题。
> 
好欸！这个思路有道理的……以后会考虑添加，吧（
> > （比如在读论文的时候小窗呼出浏览器，就能分析屏幕上的文字，针对这个提出建议……
> > （不过可能会有隐私上的问题（
> 
> 至于类似这种操作，即使不考虑隐私问题，我也有下面两方面的担忧：
> 
>  * 华为不允许[**手机和平板**](https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-screenshot-V5#screenshotpick)上的用户应用调用截图API，所以只能靠手动截图再传给浏览器。如此而言，用户完全可以直接长按小白条唤出一个权限更高的小艺来读屏-解析。
> 
>  * 个人感觉，一个浏览器，最重要的还是维护好核心功能，也就是网页浏览。对于一个已经可以很方便地完成的操作，没必要再做一个小艺的壳子放在应用内？
> 
这倒是确实……还是要遵循 Keep It Simple 的原则
> 
> > 顺便想到，搜索引擎快捷切换估计也会在近期（说不准）做出来！:D
> 
> 不知道你说的这个快捷切换，指的是不是在搜索的时候可以选择不同的搜索引擎？听上去很棒：）

Yes！类似做一个按钮选择切换之类的（有点像 Firefox 安卓上的那种，或者过几天想出一个更棒的主意）

**Comment by awaLiny2333** [comment]
添加了 Baidu 和 Google 作为预设的搜索引擎！
（但是目前它们只会在第一次启动时被添加，尚未有办法在已经开始使用的浏览器上恢复……
需要一个“恢复删除的预设”按钮吗（？

**Comment by xymeng16** [comment]
可以参考一下我这个实现（还没有太优化），但是不知道符不符合你的编码习惯。https://github.com/xymeng16/LinysBrowser_NEXT/commit/fe7e18c167472faa44cf1265adebd8b183e751a2#diff-61cbd4ab7439fb1765019d427f677f2628fcc72859997441974b440066c909f9

**Comment by awaLiny2333** [comment]
喔～这就去看看！谢谢！！！

**Comment by awaLiny2333** [comment]
> 可以参考一下我这个实现（还没有太优化），但是不知道符不符合你的编码习惯。[xymeng16@fe7e18c#diff-61cbd4ab7439fb1765019d427f677f2628fcc72859997441974b440066c909f9](https://github.com/xymeng16/LinysBrowser_NEXT/commit/fe7e18c167472faa44cf1265adebd8b183e751a2#diff-61cbd4ab7439fb1765019d427f677f2628fcc72859997441974b440066c909f9)

这个太棒了！
不过搜索引擎和建议 api 绑定可能不太符合 Liny 的个人习惯（？可能 Liny 还要再研究下……

总之，还是，太感谢了！这些代码实现能帮到很大的忙（特别是通信和 xml 解析！！！
(〃￣︶￣)人(￣︶￣〃)

**Comment by xymeng16** [comment]
不用客气，也很感谢你开源了这么轻快且优秀的浏览器～我就先关闭啦，如果有后续还可以继续回复。
