### ISSUE TITLE
功能建议：标签页中点击标签后自动收起标签页

### ISSUE THREAD

**Issue by Luxcis** [awaLiny2333/LinysBrowser_NEXT#12]
在打开标签页切换标签后不会自动收起，同时标签切换完成后点击旁边的页面也不会自动收起反而会触发页面的正常功能，这有点反直觉。

**Comment by awaLiny2333** [comment]
> 在打开标签页切换标签后不会自动收起，同时标签切换完成后点击旁边的页面也不会自动收起反而会触发页面的正常功能，这有点反直觉。

这倒是真……
Liny 争取最近研究下（可能要 1~2 个工作日）……谢谢您！！！

**Comment by awaLiny2333** [comment]
> 在打开标签页切换标签后不会自动收起，同时标签切换完成后点击旁边的页面也不会自动收起反而会触发页面的正常功能，这有点反直觉。

在非平板模式下切换标签页会自动关闭面板了！请查收～
如果反馈没有问题的话这个 Issue 就可以关掉啦！ヽ(￣ω￣(￣ω￣〃)ゝ

**Comment by Luxcis** [comment]
> > 在打开标签页切换标签后不会自动收起，同时标签切换完成后点击旁边的页面也不会自动收起反而会触发页面的正常功能，这有点反直觉。
> 
> 在非平板模式下切换标签页会自动关闭面板了！请查收～ 如果反馈没有问题的话这个 Issue 就可以关掉啦！ヽ(￣ω￣(￣ω￣〃)ゝ

没问题 太棒了！(･ω･)b
