### ISSUE TITLE
缩放问题

### ISSUE THREAD

**Issue by Weijia-Tong** [awaLiny2333/LinysBrowser_NEXT#14]
![screenshot_20241115_192811](https://github.com/user-attachments/assets/7ccdb1d1-cbb7-4733-a761-602123aa8586)
还有一个问题就是，好像即使Android和ios的ua缩放比例也会有问题欸

**Comment by awaLiny2333** [comment]
怪事，有可能是 Bing 使用了另一些检测 UA 或者选择布局的方法……UA 和网址发一下（？

**Comment by Weijia-Tong** [comment]
网址就是www.bing.com
ua我直接写的ios
是我操作问题吗（）

**Comment by awaLiny2333** [comment]
把 ua 设置成
`Mozilla/5.0 (iPhone 6s; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 MQQBrowser/8.3.0 Mobile/15B87 Safari/604.1 MttCustomUA/2 QBWebViewType/1 WKType/1` 
试试？

**Comment by awaLiny2333** [comment]
> 网址就是www.bing.com ua我直接写的ios 是我操作问题吗（）

> 把 ua 设置成
> `Mozilla/5.0 (iPhone 6s; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 MQQBrowser/8.3.0 Mobile/15B87 Safari/604.1 MttCustomUA/2 QBWebViewType/1 WKType/1`
> 试试？
> 这是 iPhone6s 的某个 UA (～o￣3￣)～

现在如何了（？

**Comment by Weijia-Tong** [comment]
解决了 (oﾟvﾟ)ノ

**Comment by awaLiny2333** [comment]
> 解决了 (oﾟvﾟ)ノ

好耶！
