### ISSUE TITLE
建议把讨论开了

### ISSUE THREAD

**Issue by sseaan** [awaLiny2333/LinysBrowser_NEXT#2]
可以把讨论开了，不然就会像我一样写史都来写Issue🤓
可以把待开发功能放README
平板加PC模式建议换UA改成横版标签栏还有操作逻辑，可以参考Chrome的电脑模式，Via的电脑模式不知道为什么Zeabur识别不了

**Comment by HandwerSTD** [comment]
大屏适配我感觉用竖向标签蛮好，多开标签页的时候相比横向标签页效率更高，我电脑也用edge的垂直标签页模。当然多一个选择也无妨

**Comment by sseaan** [comment]
> 大屏适配我感觉用竖向标签蛮好，多开标签页的时候相比横向标签页效率更高，我电脑也用edge的垂直标签页模。当然多一个选择也无妨

竖向确实有竖向的好处，标题栏放顶部会好点

**Comment by awaLiny2333** [comment]
1. 讨论：已开！(〃￣︶￣)人(￣︶￣〃)
2. 待开发功能写 README：懒得写被发现了（逃（有空就去写 (～o￣3￣)～
3. UA：自定义 UA 相关设置已经在计划中（但是不确定什么时候登场（最近比较忙
4. 标签栏＆标题栏位置安放：当前的设计是 100% 依靠 Liny 个人的使用习惯来的，所以以后可能会推出开关！
5. 感谢你！！！！！

**Comment by awaLiny2333** [comment]
标题栏可以放在顶部了！
The Title Bar can now be put at the top!

**Comment by awaLiny2333** [comment]
自定义 UA 已上线！

**Comment by 183868hlj** [comment]
有安卓版？？~~~~

**Comment by awaLiny2333** [comment]
> 有安卓版？？~~~~

当然……没有（
对不起 (´･_･`)

**Comment by 183868hlj** [comment]
> > 有安卓版？？~~~~
> 
> 当然……没有（
> 对不起 (´･_･`)

没事，不用说对不起~

**Comment by awaLiny2333** [comment]
> 可以把讨论开了，不然就会像我一样写史都来写Issue🤓 可以把待开发功能放README 平板加PC模式建议换UA改成横版标签栏还有操作逻辑，可以参考Chrome的电脑模式，Via的电脑模式不知道为什么Zeabur识别不了

推出了横向的标签页栏……可能有点怪…… /_ \\
不过总算是做出来了，应该很快能关掉这个 Issue！

**Comment by Weijia-Tong** [comment]
考虑做一下对drm加密内容播放的支持吗（

**Comment by awaLiny2333** [comment]
> 考虑做一下对drm加密内容播放的支持吗（

这个可能要研究下 ArkWeb 特性了…… Liny 有空会去看看的！谢谢您！！！

**Comment by awaLiny2333** [comment]
> 考虑做一下对drm加密内容播放的支持吗（

可以单独启动一个 Issue 以提醒健忘的 Liny ！！！

**Comment by awaLiny2333** [comment]
全部去 Discussions！这个 Issue 要关门啦！
Go to Discussions for discussions! This Issue is closing～
