### ISSUE TITLE
提个小需求（网页深色模式）

### ISSUE THREAD

**Issue by 000wbh000** [awaLiny2333/LinysBrowser_NEXT#22]
能否添加一个开关，可以对网页启用深色\黑暗模式，据我所知chromium内核就原生支持这个功能，应该大概不难。
具体效果就是网页由白底变黑底，对眼睛刺激更小了，就类似以前的华为浏览器开启夜间模式那样。
谢谢~

**Comment by awaLiny2333** [comment]
nice！这个功能终于有人提了（又要去翻文档了（ヘ(￣ω￣ヘ)
感谢你！！

预计可能需要2～5个工作日更新……感谢支持（（

**Comment by 000wbh000** [comment]
太棒啦~
这是我在鸿蒙用到的界面设计最舒服的浏览器，Liny加油！

**Comment by awaLiny2333** [comment]
太感动了 (ﾟ´Д｀ﾟ)ﾟ ……谢谢你！！！

**Comment by awaLiny2333** [comment]
> 太棒啦~ 这是我在鸿蒙用到的界面设计最舒服的浏览器，Liny加油！

推送了 Commit！！！快来看看！！！( •̀ ω •́ )✧

**Comment by 000wbh000** [comment]
看到了——
1。6。4版本feat: Web dark mode;
代码虽然不太懂，但还是看见了最后加上的致谢名单，感动(> <)
最后期待新版本封装上线啦~

**Comment by awaLiny2333** [comment]
> 看到了—— 1。6。4版本feat: Web dark mode; 代码虽然不太懂，但还是看见了最后加上的致谢名单，感动(> <) 最后期待新版本封装上线啦~

已经有 Release 啦！

**Comment by 000wbh000** [comment]
已经用上了，深色模式在各个网站上的表现都没有问题！
不过有些细节的东西还是要提一下：
在网页跳转\新页面加载时，有高概率会闪烁白色背景。
比如搜索B站，从搜索结果点进网站，就会有约半秒的白屏。
页面开始加载时的白色背景在平时无所谓，但在深色模式就会像吃闪光弹一样了。
感觉我还是被以前的浏览器惯坏了（笑哭），当然如果Liny能优化一下的话，我会感激不尽的！

**Comment by awaLiny2333** [comment]
这个感觉上像是加载的问题……在开始加载新页面的一瞬间，页面会被清空（变成白的），直到网页被一点点加载出来……但问题就在于加载出来所需的时间内，这个网页都是空的（白的）
Firefox 的处理是……使用主题色打底，但是不确定在鸿蒙的 Web 上能不能改变背景颜色……所以 Liny 回去试试看先，感谢 Issue！！！
OwO

**Comment by awaLiny2333** [comment]
> 已经用上了，深色模式在各个网站上的表现都没有问题！ 不过有些细节的东西还是要提一下： 在网页跳转\新页面加载时，有高概率会闪烁白色背景。 比如搜索B站，从搜索结果点进网站，就会有约半秒的白屏。 页面开始加载时的白色背景在平时无所谓，但在深色模式就会像吃闪光弹一样了。 感觉我还是被以前的浏览器惯坏了（笑哭），当然如果Liny能优化一下的话，我会感激不尽的！

似乎修好了！（还没有推出新的 Release，不过可以下载这些附件先试试……！OwO）
[Pre-release-1.6.4.fix1.zip](https://github.com/user-attachments/files/18075255/Pre-release-1.6.4.fix1.zip)

**Comment by 000wbh000** [comment]
已安装。体验良好，基本没有问题了。
以及，居然不到半天就弄好了，神速诶！

**Comment by awaLiny2333** [comment]
> 已安装。体验良好，基本没有问题了。 以及，居然不到半天就弄好了，神速诶！

因为发现有现成的 .backgroundColor() 属性可以用（（（被 ArkUI 拯救的一天（

（还有一个小发现》如果加载的 html 文件里没有 Body 那么就会直接显示 Web 的背景颜色（于是顺带更新了别的某些内容……精简了代码！

感谢你！！！！( •̀ ω •́ )✧
