### ISSUE TITLE
提一些小建议 - 快捷键＆一键全选 Bug

### ISSUE THREAD

**Issue by 000wbh000** [awaLiny2333/LinysBrowser_NEXT#28]
1。可不可以做几个快捷键映射，比如ctrl+T打开新标签页，ctrl+H打开历史，F11全屏之类的。
2。鼠标点击地址栏，希望能直接进入全选的状态，方便直接输入。（附图）（不是鼠标而是手指点击屏幕是有这个效果的）
希望越来越好！
![screenshot_20241222_214848](https://github.com/user-attachments/assets/b96e0e98-779a-4772-9549-2db466a71996)

**Comment by awaLiny2333** [comment]
1. 快捷键映射是好主意！会添加的！
2. TextInput 似乎有一个属性叫 selectAll，可以在 focus 的时候全选文本，不过看这段描述来……似乎不对鼠标起效（？

![image](https://github.com/user-attachments/assets/4f841dcd-aa63-4206-a5da-7d3f1e82615c)

这个倒有可能是 OpenHarmony／HarmonyOS 系统的问题了（

不过居然真的有人会用鼠标操作这个 app ……话说 DevEco Studio 的模拟器有什么办法模拟鼠标吗（？Liny 还没有真机（

**Comment by awaLiny2333** [comment]
> 2. TextInput 似乎有一个属性叫 selectAll，可以在 focus 的时候全选文本，不过看这段描述来……似乎不对鼠标起效（？
> 
> 这个倒有可能是 OpenHarmony／HarmonyOS 系统的问题了（

（悄悄话：也许可以去跟华为报告这个问题（赚取礼品（？ヽ(￣ω￣(￣ω￣〃)ゝ

**Comment by 000wbh000** [comment]
有个新发现：鼠标单击后长按（大概一秒后松开）就是正常的全选了。
不过在华为浏览器里，是单击即全选，长按就是正常编辑（居然反过来了）
奇怪的问题，不过既然有新用法，也可以不着急修了~

**Comment by awaLiny2333** [comment]
> 有个新发现：鼠标单击后长按（大概一秒后松开）就是正常的全选了。 不过在华为浏览器里，是单击即全选，长按就是正常编辑（居然反过来了） //奇怪的问题，不过既然有新用法，也可以不着急修了 有可能的话（或者将来？），还是修一修((

好像单击一次、双击、三击的操作都不一样（？似乎是神秘的小技巧（？至少在 HarmonyOS 4.2 上是这样的
Liny 更倾向于这个 selectAll 失效是 Bug

**Comment by 000wbh000** [comment]
我也觉得是bug，需要日志吗？

**Comment by awaLiny2333** [comment]
> 我也觉得是bug，需要日志吗？（我可以录一段）

应该……Liny 拿到这个日志也没啥用，不如去跟华为反映吧（（
话说有什么希望添加的快捷键吗？现在可以跟 Liny 罗列一下……下几个版本做进去！

**Comment by 000wbh000** [comment]
可以做一些浏览器通用的快捷键：

1. 打开新标签页：Ctrl+T
2. 打开历史记录：Ctrl+H
3. 焦点移到地址栏：Alt+D
4. 查找页面内容：Ctrl+F
5. 全屏：F11
6. 打开标签页列表：Ctrl+Shift+A

**Comment by awaLiny2333** [comment]
![image](https://github.com/user-attachments/assets/97f8cf28-4cbe-4010-ba18-299d526ac123)
推送了！但是 Liny 没有真机，不能测试（

**Comment by awaLiny2333** [comment]
话说能不能麻烦你帮 Liny 测试一下……？
感觉可能会有以下几种结果 :P
1. 全部都能用
2. 有的能用，有的没反应
3. 全部都没反应
4. App 崩溃了！
或者有更烂的结果发生…… ( •_•)>⌐■-■
谢谢你！！！

**Comment by awaLiny2333** [comment]
新的 build 在 [build_auto](https://github.com/awaLiny2333/LinysBrowser_NEXT/tree/master/build_auto) 里，可以去看看……

**Comment by 000wbh000** [comment]
测试了！结果是——
2 /
大部分都能正常使用，只有ctrl+F是没反应

**Comment by awaLiny2333** [comment]
> 测试了！结果是—— 2 / 大部分都能正常使用，只有ctrl+F是没反应

这么奇怪 ( •_•)>⌐■-■

**Comment by awaLiny2333** [comment]
喔，似乎知道为什么了，可能
```
                 .keyboardShortcut(!this.showing_scratching_board ?
                this.bunch_of_key_shortcuts.focus_address.main_key : '',
                  this.bunch_of_key_shortcuts.focus_address.modifier)
```
这个东西对 TextInput 不起作用（得手动 Focus

**Comment by awaLiny2333** [comment]
不对，试一下 ALT D 能不能锁到地址栏？

**Comment by awaLiny2333** [comment]
> 完全正常的（包括全选状态
> 
> > 不对不对，试一下 ALT D 能不能锁到地址栏？

Liny 猫脑过载了，稍等……可能要思考一会儿…… 

![冷冷的暴雨在脸上胡乱的拍](https://github.com/user-attachments/assets/eb9adbe2-e81f-4304-8e49-f5e5a9b6b89f)

**Comment by 000wbh000** [comment]
其实前面的那几个快捷键已经帮了大忙了！这个倒是以后经验丰富了再修不迟。不过如果Liny需要的话，我可以录一段日志给你

**Comment by awaLiny2333** [comment]
> 其实前面的那几个快捷键已经帮了大忙了！这个倒是以后经验丰富了再修不迟。不过如果Liny需要的话，我可以录一段日志给你

似乎有一点眉目……试试打开更多选项（屏幕内显示着页面内搜索的搜索框）的情况下按 Ctrl + F？
有一种可能是，选中了，但是没有弹出来（

**Comment by 000wbh000** [comment]
深意啊，真的是这样！现在找到问题所在了

**Comment by awaLiny2333** [comment]
也许修好了！
新版本已经推送到 [build_auto](https://github.com/awaLiny2333/LinysBrowser_NEXT/tree/master/build_auto) 还得继续麻烦检查一下 Liny 的『作业』了 ヽ(￣ω￣(￣ω￣〃)ゝ

**Comment by 000wbh000** [comment]
Liny太谦虚了！
 经测试，已经可以使用了！这个问题也可以告一段落。
其实我发觉自己有些操之过急了，模拟器对键鼠这块居然是缺失的，应该等鸿蒙PC出来就完善了，那时候就会简单许多。
Ps: 虽然说昨晚不太“平安”吧，但今天在此祝Liny圣诞快乐！！

**Comment by awaLiny2333** [comment]
> Liny太谦虚了！ 经测试，已经可以使用了！这个问题也可以告一段落。 其实我发觉自己有些操之过急了，模拟器对键鼠这块居然是缺失的，应该等鸿蒙PC出来就完善了，那时候就会简单许多。 Ps: 虽然说昨晚不太“平安”吧，但今天在此祝Liny圣诞快乐！！

好耶！
这种适配问题早发现也是好事——谢谢！！！Merry Christmas!!
