### ISSUE TITLE
UI Visual Effect Issue: Intentional Green Background?

### ISSUE THREAD

**Issue by SoildFaker** [awaLiny2333/LinysBrowser_NEXT#3]
I'm not sure if this was intentional, but on my device, every time I open the keyboard on a webpage, there's a green background that flashes, which looks quite abrupt and out of place.

https://github.com/awaLiny2333/LinysBrowser_NEXT/blob/16f299fe5f769a2fe4ffc334813c4a5c835871af/home/src/main/ets/blocks/LinysWebView.ets#L97

**Comment by awaLiny2333** [comment]
Oh oops that seems to be a debug stuff that is luckily (or unluckily) remained in the finished function codes...

**Comment by awaLiny2333** [comment]
Removed. Will be updated in next push! 
THANK YOU!! (=｀ﻌ´=)
