### ISSUE TITLE
书签不能编辑在文件夹中的位置吗

### ISSUE THREAD

**Issue by lsxuan12138** [awaLiny2333/LinysBrowser_NEXT#6]
如题，edge导出的书签导入进来后会在外面套几层文件夹，能不能加个更改位置的功能。或者有什么办法可以临时解决下吗？

**Comment by lsxuan12138** [comment]
好的 好的 感谢回复 期待增加功能

**Comment by awaLiny2333** [comment]
> 好的 好的 感谢回复 期待增加功能

已经初步实现！请查收！
（如果发现有什么事情不对，麻烦反馈给 Liny 去修（（(～o￣3￣)～ 谢谢你！！

**Comment by lsxuan12138** [comment]
简单使用了下，目前没有问题
