### ISSUE TITLE
希望劫持返回手势

### ISSUE THREAD

**Issue by xymeng16** [awaLiny2333/LinysBrowser_NEXT#8]
目前的返回手势一旦触发会直接返回桌面，希望可以劫持返回手势为返回上一页：）

**Comment by awaLiny2333** [comment]
喔，终于有人提出这件事情了！
估计会做成按钮吧（大概（

感谢 Issue！！！
预计在 3 日内 Push……

**Comment by awaLiny2333** [comment]
已 Push！请查收～
＊快速开发的代码可能含有若干潜在问题，因此尚未 Build 为新 Release！
＊如果遇到任何问题，请直接在此 Issue 下回复～

**Comment by xymeng16** [comment]
> 已 Push！请查收～ ＊快速开发的代码可能含有若干潜在问题，因此尚未 Build 为新 Release！ ＊如果遇到任何问题，请直接在此 Issue 下回复～

感谢，明天回到办公室就build测试。
P.S. 说好的3日内，也太快了，点赞👍

**Comment by awaLiny2333** [comment]
> > 已 Push！请查收～ ＊快速开发的代码可能含有若干潜在问题，因此尚未 Build 为新 Release！ ＊如果遇到任何问题，请直接在此 Issue 下回复～
> 
> 感谢，明天回到办公室就build测试。 P.S. 说好的3日内，也太快了，点赞👍

三天过去啦……感觉如何（？有无遇到任何相关的问题（？
(　o=^•ェ•)o　┏━┓

**Comment by xymeng16** [comment]
> > > 已 Push！请查收～ ＊快速开发的代码可能含有若干潜在问题，因此尚未 Build 为新 Release！ ＊如果遇到任何问题，请直接在此 Issue 下回复～
> > 
> > 
> > 感谢，明天回到办公室就build测试。 P.S. 说好的3日内，也太快了，点赞👍
> 
> 三天过去啦……感觉如何（？有无遇到任何相关的问题（？ (　o=^•ェ•)o　┏━┓

不好意思，Mac坏掉了，现在只有一台Linux，没有DevEco环境，没法构建了T_T，等修好第一时间测试。

**Comment by awaLiny2333** [comment]
> > > > 已 Push！请查收～ ＊快速开发的代码可能含有若干潜在问题，因此尚未 Build 为新 Release！ ＊如果遇到任何问题，请直接在此 Issue 下回复～
> > > 
> > > 
> > > 感谢，明天回到办公室就build测试。 P.S. 说好的3日内，也太快了，点赞👍
> > 
> > 
> > 三天过去啦……感觉如何（？有无遇到任何相关的问题（？ (　o=^•ェ•)o　┏━┓
> 
> 不好意思，Mac坏掉了，现在只有一台Linux，没有DevEco环境，没法构建了T_T，等修好第一时间测试。

惨 :( 希望电脑没事🙏

**Comment by xymeng16** [comment]
Mac搞好了，刚刚测试发现返回手势劫持正常工作，万分感谢：）辛苦啦
